In [ ]:
Installation of numpy

In [1]:
:pip install numpy

SyntaxError: invalid syntax (<ipython-input-1-f8254107343e>, line 1)

In [4]:
import numpy as np

In [5]:
array_one = np.array([1,2,3,4])

array_one

array([1, 2, 3, 4])

In [6]:
type(array_one)

numpy.ndarray

In [8]:
numbers = [9,8,7,6,5,4,3,2,1,]

array_two = np.array(numbers)

array_two

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [10]:
numbers = [4,5,6,7]

array_three = np.array(numbers)

array_three

array([4, 5, 6, 7])

In [11]:
type(array_three)

numpy.ndarray

In [13]:
array_of_zeros = np.array((3,4))

array_of_zeros

array([3, 4])

In [14]:
array_of_zeros = np.zeros((3,4))

array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
array_of_ones = np.ones((4,3))

array_of_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
To remove Dots / Decimal

In [20]:
array_of_ones_int = np.ones((3,4),dtype=np.int16)

array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [24]:
array_of_ones_int = np.ones((3),dtype=np.int16)

array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)