In [ ]:
1D array implimentation

In [1]:
import numpy as np

In [11]:
a = np arange(11)**2

a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [16]:
a = np.arange(10)**2

a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [17]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0


In [ ]:
Multi Dimensional array

In [18]:
students = np.array([['papi','sneha','kumar','ameen'],
                    [65,70,75,80],
                    [85,80,75,70]])

In [21]:
for i in students:
    print('i=',i)

i= ['papi' 'sneha' 'kumar' 'ameen']
i= ['65' '70' '75' '80']
i= ['85' '80' '75' '70']


In [ ]:
iteation over the each & every element

In [ ]:
using method flatten 

In [23]:
for element in students.flatten():
    print(element)

papi
sneha
kumar
ameen
65
70
75
80
85
80
75
70


In [ ]:
Req:I want to have an column based spiliting

In [ ]:
syntax will be changed lighty

In [32]:
for element in students.flatten(order='F'):
    print(element)

papi
65
85
sneha
70
80
kumar
75
75
ameen
80
70


In [ ]:
implimentation of nditer:

In [25]:
x= np.arange(12).reshape(3,4)

x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
Row based ordering

In [26]:
for i in np.nditer(x):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [31]:
for i in np.nditer(x, order = 'F'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11
