In [1]:
import numpy as np

In [ ]:
Req: Implimenting an identity matrix

In [2]:
array_eye = np.eye(4)

array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
array_eye = np.eye(8)

array_eye

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
Req: I want to print the number b/w 0,20 by using numpy

In [11]:
array_two = np.arange(0,20)

array_two

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
array_ones = np.arange(0,25)

array_ones

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
REq: Array ot even numnber (2,30) in this range i want to print 

In [13]:
array_even =np.arange(2,30,2)

array_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
Req : by using the array print the odd number from 0 to 30        # Homw work Ques

In [19]:
array_odd = np.arange(3,30,2)

array_odd

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [ ]:
Req: To have range of number till 6

In [21]:
x= np.arange(6)  # 1 Dimensional

x

array([0, 1, 2, 3, 4, 5])

In [22]:
x.shape

(6,)

In [ ]:
Req: How to create an 2 dimensional aray by using the samne

In [24]:
array_ab = x.reshape(2,3)

array_ab

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
array_ab.shape

(2, 3)

In [26]:
array_ab = x.reshape(2,4)

array_ab

ValueError: cannot reshape array of size 6 into shape (2,4)

In [27]:
A = np.arange(30)

A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
B = A.reshape(10,3)

B

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [29]:
A = np.arange(30)

A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
B = A.reshape(3,10)

B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])